IntelliPrestamos/Controllers/DocumentosController.cs
using IntelliPrestamo.AccessLayer.AppTools;
using IntelliPrestamo.AccessLayer.DataManager;
using IntelliPrestamos.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IntelliPrestamos.Controllers
{
    public class DocumentosController : BaseController.BaseController
    {
        private DocumentManager manager;
        //
        // GET: /Cargo/

        public ActionResult Manage()
        {
            bussinessInfo();
            return GetAll("");
        }

        public ActionResult Get(int Id_Rol, string partial_view)
        {
            manager = new DocumentManager();
            var result = manager.GetById(Id_Rol);
            ViewBag.drpFlujo = GetDrpFlujo();
            SystemVariableManager sisVar = new SystemVariableManager();
            ViewBag.VariablesSystema = sisVar.Get();
            return PartialView(partial_view, result);
        }

        public ActionResult DownloadDoc(int solicitud_id, int prestamo_id, string cedula, int document_id)
        {
            manager = new DocumentManager();
            var result = manager.DocumentParseWithVariables(solicitud_id, prestamo_id, cedula, document_id);
            var documentObject = manager.GetById(document_id);
            string loc = Server.MapPath("~/");
            PDFConverter pdf = new PDFConverter();
            string fileName = pdf.GeneratePdfFromString(result, documentObject.Nombre_Documento, /*ConfigurationManager.AppSettings["LocalRoot"]*/loc, ConfigurationManager.AppSettings["RemoteRoot"]);
            return File(fileName, "application/pdf", documentObject.Nombre_Documento+".pdf"); ;
        }
         public ActionResult DownloadHtmlReports(string Action, string Url)
        {
            PDFConverter pdf = new PDFConverter();
            string loc = Server.MapPath("~/");
            string fileName = pdf.GeneratePdfFromUrl(Action, loc /*ConfigurationManager.AppSettings["LocalRoot"]*/, Url, ConfigurationManager.AppSettings["RemoteRoot"] + "/");
            return File(fileName, "application/pdf", Action + ".pdf"); ;
        }
         public ActionResult DownloadImageReports(string fileName)
         {
             string path = Server.MapPath("~/content/") + fileName;
             string extension = Path.GetExtension(path);
             string filename = Path.GetFileName(path);
             return File(path, "application/" + extension, filename); 
         }
        public ActionResult GetAll(string partial_view)
        {
            manager = new DocumentManager();
            var result = manager.Get();
            if (string.IsNullOrEmpty(partial_view))
            {
                return View(result);
            }
            return PartialView(partial_view, result);
        }
        [HttpPost]
        [ValidateInput(false)]        
        public ActionResult Add(Document model)
        {
            try
            {
                manager = new DocumentManager();
                manager.Set(model);
                
                ViewBag.Success = "Datos Actualizados Satisfactoriamente";
                return Content("Datos Actualizados Satisfactoriamente");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }

            return Content(ViewBag.Error);
        }
        
        public ActionResult Delete(Document model)
        {
            try
            {
                manager = new DocumentManager();
                manager.Del(model);

                ViewBag.Success = "Datos Actualizados Satisfactoriamente";
                return Content("Datos Actualizados Satisfactoriamente");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }

            return Content(ViewBag.Error);
        }
	}
}

IntelliPrestamos/Controllers/PagosController.cs
using IntelliPrestamo.AccessLayer.AppTools;
using IntelliPrestamo.AccessLayer.DataManager;
using IntelliPrestamos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IntelliPrestamos.Controllers
{
    public class PagosController : BaseController.BaseController
    {
        private PrestamosManager manager;
        private CuotasManager CuoManager;
        private PagoManager PagoManager;
        private MoraManager moraManager;
        //
        // GET: /Pagos/
        public ActionResult Manage()
        {
            try
            {
                Prestamos loan = new Prestamos();
                initiateDropDownSolicitud();
                bussinessInfo();
                return View(loan);
            }
            catch(Exception ex)
            {
                Set_Message("Ha Ocurrido Un Error: " + ex.Message);
            }
            return View();
        }
        public ActionResult Pendientes()
        {
            try
            {
                manager = new PrestamosManager();
                initiateDropDownSolicitud();
                bussinessInfo();
                var result = manager.GetByLoanPending(Cedula);
                return View(result);
            }
            catch(Exception ex)
            {
                Set_Message("Ha Ocurrido Un Error: " + ex.Message);
            }
            return View();
        }
        public ActionResult Notificaciones()
        {
            try
            {
                manager = new PrestamosManager();
                initiateDropDownSolicitud();
                bussinessInfo();
                var result = manager.GetByLoanPendingAll();
                foreach(Prestamos prestamo in result)
                {
                    UsuarioManager empleado = new UsuarioManager();
                    if (prestamo.Cobrador != null)
                    {
                        var usuario = empleado.GetBy(prestamo.Cobrador);
                        sendMail(usuario.Email, "Pago Prestamo Pendiente #" + prestamo.Prestamo_Id.ToString(),
                            "El prestamo #" +
                            prestamo.Prestamo_Id.ToString() + " presenta atrasos.");
                    }

                    if (prestamo.Accionista != null)
                    {
                        var usuario = empleado.GetBy(prestamo.Accionista);
                        sendMail(usuario.Email, "Pago Prestamo Pendiente #" + prestamo.Prestamo_Id.ToString(),
                            "El prestamo #" +
                            prestamo.Prestamo_Id.ToString() + " presenta atrasos.");
                    }
                }
                return Content("Notificaciones Enviados...");
            }
            catch(Exception ex)
            {
                Set_Message("Ha Ocurrido Un Error: " + ex.Message);
            }
            return Content("");
        }
        
        public ActionResult Incobrable(int prestamo_id)
        {
            try
            {
                manager = new PrestamosManager();
                manager.Del(prestamo_id);
            }
            catch(Exception ex)
            {
                return Content(ex.Message);
            }
            return Content("Datos Guardados Exitosamente");
        }
        public ActionResult GetPrestamos(int prestamo_id, string partial_view)
        {
            manager = new PrestamosManager();
            var result = manager.Get( prestamo_id);
            return PartialView(partial_view, result);
        }
        public ActionResult GetAll(string cedula, int solicitud_id, int prestamo_id,string accionista,string partial_view)
        {
            manager = new PrestamosManager();
            bussinessInfo();
            var result = manager.GetPayment(cedula, solicitud_id, prestamo_id, Cedula);
            return PartialView(partial_view, result);
        }

        public ActionResult GetCuotaAndPayments(int Id_Rol, string partial_view)
        {
            CuoManager = new CuotasManager();
            PagoManager = new PagoManager();
            moraManager = new MoraManager();
            manager = new PrestamosManager();
            var result = CuoManager.Get(Id_Rol);
            List<CuotaPagoViewModel> CuotaPago = new List<CuotaPagoViewModel>();
            int counter = 0;
            foreach (Cuotas cuota in result)
            {
                CuotaPagoViewModel viewModel = new CuotaPagoViewModel();
                viewModel.cuota = cuota;
                viewModel.pago = PagoManager.Get(cuota.Prestamos_Id,cuota.Numero_Cuota);
                viewModel.mora = moraManager.Get(cuota.Prestamos_Id, cuota.Numero_Cuota); 
                CuotaPago.Add(viewModel);
                counter++;
            }
            ViewBag.Prestamos = manager.Get(Id_Rol); 
            return PartialView(partial_view, CuotaPago);
        }
        [HttpPost]       
        public ActionResult SetCuotaPayments(int id_prestamo, int numero_cuotas, decimal monto, int mora_status)
        {
            string error = "";
            try
            {
                PagoManager = new PagoManager();
                PagoManager.Set(id_prestamo, numero_cuotas, monto, mora_status);
                manager = new PrestamosManager();
                UsuarioManager empleado = new UsuarioManager();
                var resultPrestamo = manager.Get(id_prestamo);
                var Accionista = empleado.GetBy(resultPrestamo.Accionista);
                bussinessInfo();
                sendMail(Accionista.Email, "Pago Cuota Prestamo #" + id_prestamo.ToString() + " cuota #" + numero_cuotas.ToString(), "Se ha hecho un pago al numero de prestamo #" + id_prestamo.ToString() + " por el monto de " + monto.ToString() + ".");
            }
            catch(Exception ex)
            {
                error = ex.Message;
            }
            return Content(error);
        }

        
        [HttpPost]        
        public ActionResult SetCuotaPaymentsExtra(int id_prestamo, decimal monto, int afecta_prestamos)
        {
            string error = "";
            try
            {
                PagoManager = new PagoManager();
                PagoManager.SetExtra(id_prestamo, monto, afecta_prestamos);
                manager = new PrestamosManager();
                UsuarioManager empleado = new UsuarioManager();
                var resultPrestamo = manager.Get(id_prestamo);
                var Accionista = empleado.GetBy(resultPrestamo.Accionista);
                bussinessInfo();
                sendMail(Accionista.Email, "Pago Extraordinario Prestamo " + id_prestamo.ToString(), "Se ha hecho un pago al numero de prestamo #" + id_prestamo.ToString() + " por el monto de " + monto.ToString() + ".");
            }
            catch (Exception ex)
            {
                error = ex.Message;
            }
            return Content(error);
        }
        public ActionResult VolantesDePago( int prestamo_id, int numero_cuota, int pago_id)
        {
            PagoManager = new PagoManager();
            bussinessInfo();
            var result = PagoManager.GetPays(prestamo_id, numero_cuota, pago_id);
            return View("VolantesDePago", result);
        }
        public ActionResult TablaAmortizacion(int prestamo_id)
        {
            TablaAmortizacionManager tabla = new TablaAmortizacionManager();
            bussinessInfo();
            var result = tabla.Get(prestamo_id);
            return View("TablaAmortizacion", result);
        }
        
	}
}

IntelliPrestamos/Views/Pagos/Manage.cshtml
@model IntelliPrestamos.Models.Prestamos
@{
    ViewBag.Title = "Gestión Pagos Prestamos En Sistema";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <div class="panel-control">
            <a class="fa fa-question-circle fa-lg fa-fw unselectable add-tooltip" href="#" data-original-title="<h4 class='text-thin'>Información</h4><p style='width:150px'>Este modulo maneja los pagos a prestamos configurados en sistema.</p>" data-html="true" title=""></a>
        </div>
        <h3 class="panel-title">Gestión Pagos Prestamos</h3>
    </div>

    <div class="panel-body">
       
            <hr>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">Cedula</label>
                            <input type="text" class="form-control" value="@Model.Cedula" name="Cedula" id="Cedula" placeholder="999-9999999-9">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">Prestamo Id</label>
                            <input type="text" class="form-control" value="@Model.Prestamo_Id" name="Prestamo_Id" id="Prestamo_Id">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">Solicitud Id</label>
                            <input type="text" class="form-control" value="@Model.Id_Solicitud" name="Solicitud_Id" id="Solicitud_Id">
                             
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            @*<label class="control-label">Seleccionar Accionista</label>
                            @Html.DropDownList("Accionista", @ViewBag.DrpAccionistas as IEnumerable<SelectListItem>, new { @class = "form-control", @id = "Accionista" })*@
                        </div>
                    </div>
                </div>
           
            </div>
        <div class="panel-footer clearfix">
            <div class="panel-footer text-right">
                <span id="spnModalConfigInformation" style="color:red;">@ViewBag.Message</span>
                <button type="button" class="btn btn-info"
                        onclick="showModalSearch(this, $('#Cedula').val(), $('#Prestamo_Id').val(), $('#Solicitud_Id').val(), '@ViewBag.Accionista', '_ViewLoan');"
                        data-url="@(Url.Action("GetAll", "Pagos"))">
                    Consultar
                </button>
            </div>
        </div>
        <div id="content-ajax">
           
        </div>
        <div id="content-modal_info"></div>
    </div>
</div>
@section Header{
    <link href="@Url.Content("~/Content/plugins/datatables/media/css/dataTables.bootstrap.css")" rel="stylesheet">
<link href="@Url.Content("~/Content/plugins/fooTable/css/footable.core.css")" rel="stylesheet">
}
@section scripts{
    <!--UtilitiesScripts [ Tiene las funciones especiales usadas en las vistas ]-->
    <script src="@Url.Content("~/Content/js/UtilitiesScripts.js")"></script>
<script src="@Url.Content("~/Content/plugins/masked-input/jquery.maskedinput.min.js") "></script>
<script type="text/javascript">
    $('#Cedula').mask('999-9999999-9');
    function setOnChangeEvent(numero_cuota)
    {
        var stringId = String(numero_cuota);
        $(function () {
            $("#CobrarMora"+stringId).change(function () {
                $("#Seleccion" + stringId).val($(this).val());
            });
        });
    }    
    </script>
    }

IntelliPrestamos/Views/Pagos/Pendientes.cshtml
@model IEnumerable<IntelliPrestamos.Models.Prestamos>
@{
    ViewBag.Title = "Gestión Pagos Prestamos En Sistema";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <div class="panel-control">
            <a class="fa fa-question-circle fa-lg fa-fw unselectable add-tooltip" href="#" data-original-title="<h4 class='text-thin'>Información</h4><p style='width:150px'>Este modulo maneja los pagos a prestamos configurados en sistema.</p>" data-html="true" title=""></a>
        </div>
        <h3 class="panel-title">Pagos Pendientes</h3>
    </div>

    <div class="panel-body">

        @*<div class="col-sm-6 table-toolbar-left">
            <button id="demo-btn-addrow" class="btn btn-purple btn-labeled fa fa-plus" data-url="@(Url.Action("Notificaciones", "Pagos"))" onclick="showModalConfig(this, '0','_Add');">Enviar Notificación</button>
        </div>*@
        <div class="pad-btm form-inline">
            <div class="row">
                <div class="col-sm-6 table-toolbar-left">
                    <button id="demo-btn-addrow" class="btn btn-purple btn-labeled fa fa-plus" data-url="@(Url.Action("Notificaciones", "Pagos"))" onclick="showModalConfig(this, '0','_Add');">Enviar Notificación</button>
                </div>
                <div class="col-sm-6 table-toolbar-right">
                    <div class="form-group">

                    </div>
                </div>
            </div>
        </div>
        @if (Model != null && Model.Count() > 0)
        {
        <div id="content-ajax">
            @Html.Partial("~/Views/Pagos/_ViewPendientes.cshtml", Model)
        </div>    
        }
        
        <div id="content-modal_info"></div>
    </div>
</div>
@section Header{
    <link href="@Url.Content("~/Content/plugins/datatables/media/css/dataTables.bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/plugins/fooTable/css/footable.core.css")" rel="stylesheet">
}
@section scripts{
    <!--UtilitiesScripts [ Tiene las funciones especiales usadas en las vistas ]-->
    <script src="@Url.Content("~/Content/js/UtilitiesScripts.js")"></script>
    <script src="@Url.Content("~/Content/plugins/masked-input/jquery.maskedinput.min.js") "></script>
    <script type="text/javascript">
        $('#Cedula').mask('999-9999999-9');
        function setOnChangeEvent(numero_cuota) {
            var stringId = String(numero_cuota);
            $(function () {
                $("#CobrarMora" + stringId).change(function () {
                    $("#Seleccion" + stringId).val($(this).val());
                });
            });
        }
    </script>
}

IntelliPrestamos/Views/Pagos/_Get.cshtml
@model IEnumerable<IntelliPrestamos.Models.CuotaPagoViewModel>
<div class="modal fade" id="modalDetail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 750px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Relación Pagos / Cuotas En Sistema</h4>
            </div>
            <div class="modal-body">
                <div class="panel">
                    <!-- Foo Table - Expand / Collapse All Rows -->
                    <!--===================================================-->
                    <div class="panel-body">
                        
                        <table id="Cuotas_Table" class="table toggle-circle">
                            <thead>
                                <tr>
                                    <th data-toggle="true"># Cuota</th>
                                    <th>Fecha Cuota</th>
                                    <th>Status</th>
                                    <th >Fecha Pago</th>
                                    <th>Mora</th>
                                    <th>Cobrar Mora</th>
                                    <th>Monto Pago</th>
                                    <th>Monto Adeuda</th>
                                    <th>Comprobante</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.cuota.Numero_Cuota</td>
                                        <td>@item.cuota.Fecha_Cuota</td>
                                        <td><span style="width: 200px;" class="label label-table label-@switch (item.cuota.Status_Desc.ToString())
                                                                                {
                                                                                    case "Pagada":
                                                                                        @("success".ToString());
                                                                                        break;
                                                                                    case "Atrasada":
                                                                                        @("danger".ToString());
                                                                                        break;
                                                                                    case "Pendiente":
                                                                                        @("danger".ToString());
                                                                                        break;
                                                                                    case "Activa":
                                                                                        @("danger".ToString());
                                                                                        break;
                                                                                    default:
                                                                                        @("dark".ToString());
                                                                                        break;
                                                                                }">@item.cuota.Status_Desc</span></td>
                                        <td>@if (item.pago != null)
                                            {
                                                @item.pago.Fecha_Pago
                                            }
                                        </td>
                                        <td>
                                            <span id="Pay@(item.cuota.Numero_Cuota)">
                                                @if (item.mora != null)
                                                {
                                                    @item.mora.Monto
                                                }
                                            </span>
                                        </td>
                                        <td>
                                            @if (item.mora != null)
                                            {
                                                @item.mora.Status_Desc
                                            }
                                        </td>
                                        <td>@if (item.pago != null)
                                            {
                                                @item.pago.Monto
                                            }
                                            </td>
                                        <td>@if (item.pago != null)
                                            {
                                                @(item.pago.Monto - item.cuota.Monto)
                                            }
                                            else
                                            {
                                                 @((-1)*item.cuota.Monto)
                                            }</td>
                                        <td>
                                            @if (item.pago != null && item.cuota.Status_Desc.ToString() == "Pagada" )
                                            {
                                                <a href="@Url.Action("DownloadHtmlReports", "Documentos", new { @Action = "VolantePagos", @Url = Url.Action("VolantesDePago", "Pagos", new { @prestamo_id = item.cuota.Prestamos_Id, @numero_cuota = item.cuota.Numero_Cuota, pago_id = 0 }) })" class="list-group-item">Descargar</a>
                                            }
                                    </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!--===================================================-->
                    <!-- End Foo Table - Expand / Collapse All Rows -->

                </div>
            </div>
            <div class="modal-footer">
                <span id="spnModalConfigInformation" style="color:red;"></span>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $('#Cuotas_Table').DataTable({
            "language": {
                "lengthMenu": "Mostrar _MENU_ Registros por Página",
                "zeroRecords": "No se encontraron coincidencias",
                "info": "Mostrando Página _PAGE_ de _PAGES_",
                "infoEmpty": "",
                "search": "Buscar:",
                "infoFiltered": "(filtered from _MAX_ total records)",
                "paginate": {
                    "first": "Primero",
                    "last": "Último",
                    "next": "Próximo",
                    "previous": "Anterior"
                }
            }
        });
    });
</script>

IntelliPrestamos/Views/Pagos/_PagosExtraordinarios.cshtml
@model IntelliPrestamos.Models.Prestamos
<div class="panel">

    <div class="panel-heading">
        <h3 class="panel-title">No. Prestamos @Model.Prestamo_Id</h3>
    </div>
    <div class="panel-body">
        <h4 class="mar-btm text-thin">Prestamos</h4>
        <hr>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">Monto Aprobado</label>
                        <input type="text" class="form-control" value="@Model.Monto_Aprobado" name="prestamos.Monto_Aprobado" id="Monto_Prestamo" readonly="true">
                        
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">Plazo</label>
                        <input type="number" class="form-control" value="@Model.Plazo" name="prestamos.Plazo" id="Plazo" readonly="true">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">Periodicidad</label>
                        <input type="text" class="form-control" value="@Model.Periodicidad_Desc" name="prestamos.Periodicidad_Desc" id="Periodicidad_Desc" readonly="true">


                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">Estado</label>
                        <input type="text" class="form-control" value="@Model.Status_Desc" name="prestamos.Status_Desc" id="Status_Desc" readonly="true">

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">Tasa Interes</label>
                        <input type="text" class="form-control" value="@Model.Interes" name="prestamos.Interes" id="Interes" readonly="true"/>


                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">Interes Generados</label>
                        <input type="text" class="form-control" value="@Model.Intereses_Generados" name="prestamos.Intereses_Generados" id="Intereses_Generados" readonly="true"/>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">Capital Pagado</label>
                        <input type="text" class="form-control" value="@Model.Capital_Pagados" name="prestamos.Capital_Pagados" id="Capital_Pagados" readonly="true" />

                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">Interes Pagado</label>
                        <input type="text" class="form-control" value="@Model.Intereses_Pagados" name="prestamos.Intereses_Pagados" id="Intereses_Pagados" readonly="true" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">Balance General</label>
                        <input type="text" class="form-control" value="@Model.Balance_General" name="prestamos.Balance_General" id="Balance_General" readonly="true" />


                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">Pago Extraordinario</label>
                        <input type="text" class="form-control" value="@Model.Balance_General" name="PagoExtraordinario" id="PagoExtraordinario"  />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">Plazo Sugerido</label>
                        <input type="number" class="form-control" value="@Model.cuotas_restantes" name="prestamos.cuotas_restantes" id="cuotas_restantes">
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer clearfix">
            <div class="panel-footer text-right">
                
                <span id="spnModalConfigInformationResult" style="color:red;"></span>
                        @if (@Model.Status_Desc != "Cancelado")
{
    <button type="button" class="btn btn-info" data-url="@(Url.Action("SetCuotaPaymentsExtra", "Pagos"))" onclick="PutPaymentsExtra(this,'spnModalConfigInformationResult' , '@Model.Prestamo_Id',$('#PagoExtraordinario').val(),  $('#cuotas_restantes').val());">Efectuar Pago</button>
}
            </div>
        </div>

    </div>

</div>