IntelliPrestamos/Controllers/SetUpController.cs
using IntelliPrestamo.AccessLayer.DataManager;
using IntelliPrestamos.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IntelliPrestamos.Controllers
{
    public class SetUpController : BaseController.BaseController
    {
        private SetUpManager manager = null;
        private RolesManager Rol = null;
        private ModuloManager Mod = null;
        //
        // GET: /SetUp/
        public ActionResult Index()
        {
            var result = bussinessInfo();
            ViewBag.DrpColor = GetDrpColor();
            return View(result);
        }

        [HttpPost]
        public ActionResult Index(Datos_Sistema model)
        {
            try
            {

                bussinessInfo();
                ViewBag.DrpColor = GetDrpColor();
                manager = new SetUpManager();
                model.Logo_Negocio = Upload_File("fileUpload", "logo");
                model.Icon = Upload_File("fileUploadIcon", "icon");
                var result = manager.Set(model);
                Set_Message("Datos Guardados Correctamente");
                return View(result);
            }
            catch (Exception ex)
            {
                Set_Message("Ha Ocurrido Un Error: " + ex.Message);
            }
            return View(model);
        }

        public ActionResult Roles()
        {
            bussinessInfo();
            return GetRoles("");
        }
        public ActionResult GetRoles(string partial_view)
        {
            Rol = new RolesManager();
            var result = Rol.Get(0);
            #region PreparandoArchivoDescarga
            string fileName = "RoleInfo.csv";            
                //Areglando lista.
                var dataReport = (from a in result
                                  select new
                                  {
                                      Id_Rol = a.Id_Rol.ToString(),
                                      Nombre_Rol = a.Nombre_Rol,
                                      Descripccion = a.Descripccion,
                                      Activo = a.Activo.ToString()
                                  }
                    ).ToList();
                Create_Excel_Reports(fileName, dataReport);
            #endregion
            if (string.IsNullOrEmpty(partial_view))
            {
                return View(result);
            }
            return PartialView(partial_view, result);
        }
        public ActionResult GetSingleRole(int Id_Rol, string partial_view)
        {
            Rol = new RolesManager();
            Mod = new ModuloManager();
            var result = Rol.Get(Id_Rol);
            var result_view = new Roles(); 
            if (result != null && result.Count > 0)
            {
                result_view = result[0];
                result_view.ListRol = Mod.Get(Id_Rol);
            }
            else
            {
                result_view.ListRol = Mod.Get(0);
            }

            return PartialView(partial_view, result_view);
        }

        public ActionResult Delete(Roles model)
        {
            try
            {
                Rol = new RolesManager();
                Mod = new ModuloManager();
                model.Activo = 0;
                var result = Rol.Set(model);

                ViewBag.Success = "Datos Actualizados Satisfactoriamente";
                return Content("Datos Actualizados Satisfactoriamente");
            }
            catch(Exception ex)
            {
                ViewBag.Error = ex.Message;
            }

            return Content(ViewBag.Error);
        }
        public ActionResult Add(Roles model)
        {
            try
            {
                Rol = new RolesManager();
                Mod = new ModuloManager();
                var result = Rol.Set(model);

                if (result != null)
                {
                    foreach (Modulos modulos in model.ListRol)
                    {
                        if (modulos.Selected)
                        {
                            Mod.Set(result.Id_Rol, modulos.Id_Modulos, 1);
                        }
                        else
                        {
                            Mod.Set(result.Id_Rol, modulos.Id_Modulos, 0);
                        }
                    }
                }
                ViewBag.Success = "Datos Guardados/Actualizados Satisfactoriamente";
                return Content("Datos Guardados/Actualizados Satisfactoriamente");
            }
            catch(Exception ex)
            {
                ViewBag.Error = ex.Message;
            }

            return Content(ViewBag.Error);
        }
        
        
	}
}

IntelliPrestamos/Controllers/UsersController.cs
using IntelliPrestamo.AccessLayer.DataManager;
using IntelliPrestamos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IntelliPrestamos.Controllers
{
    public class UsersController : BaseController.BaseController
    {

        private EmpleadoManager manager;
        //
        // GET: /Users/
        public ActionResult Manage()
        {
            bussinessInfo();
            return Get("", "");
        }
        public ActionResult GetAll(string partial_view)
        {
            manager = new EmpleadoManager();
            var result = manager.GetAll();
            return PartialView(partial_view, result);
        }
        public ActionResult Get(string Id_Rol, string partial_view)
        {
            manager = new EmpleadoManager();
            initiateDropDown();
            if (Id_Rol == "" &&
                partial_view == "")
            {
                var result = manager.GetAll();
                return View(result);
            }
            else
            {
                var result = manager.GetBy(Id_Rol);
                return PartialView(partial_view, result);
            }            
        }
        public ActionResult User(string Cedula)
        {
            bussinessInfo();
            initiateDropDown();
            manager = new EmpleadoManager();
            var result = manager.GetBy(Cedula);
            return View(result);
        }
        
        public ActionResult Add(Empleado model)
        {
            try
            {
                bussinessInfo();
                manager = new EmpleadoManager();
                initiateDropDown();
                /// SI la fecha de salida, asignar espacio en blanco
                if (model.Fecha_Salida == null )
                {
                    model.Fecha_Salida ="";
                }
                manager.Set(model);
                
                ViewBag.Message = "Datos Actualizados Satisfactoriamente";
                return View("User", model);
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }

            return View("User", model);
        }
	}
}

IntelliPrestamos/Views/SetUp/Roles.cshtml
@model IEnumerable<IntelliPrestamos.Models.Roles>
@{
    ViewBag.Title = "Roles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="panel">
    <div class="panel-heading">
        <div class="panel-control">
            <a class="fa fa-question-circle fa-lg fa-fw unselectable add-tooltip" href="#" data-original-title="<h4 class='text-thin'>Información</h4><p style='width:150px'>Este modulo muestra los Modulos de seguridad configurados en sistema.</p>" data-html="true" title=""></a>
        </div>
        <h3 class="panel-title">Gestión De Roles En Sistema</h3>
    </div>

    <div class="panel-body">
        <div class="pad-btm form-inline">
            <div class="row">
                <div class="col-sm-6 table-toolbar-left">
                    <button id="demo-btn-addrow" class="btn btn-purple btn-labeled fa fa-plus" data-url="@(Url.Action("GetSingleRole", "SetUp"))" onclick="showModalConfig(this, '0','_AddRoles');">Crear</button>
                </div>
                <div class="col-sm-6 table-toolbar-right">
                    <div class="form-group">

                    </div>
                </div>
            </div>
        </div>
        <div id="content-ajax">
            @Html.Partial("~/Views/SetUp/_ViewRoles.cshtml", Model)
        </div>
        <div id="content-modal_info"></div>
    </div>
</div>
@section Header{
  
<link href="@Url.Content("~/Content/plugins/datatables/media/css/dataTables.bootstrap.css")" rel="stylesheet">
}
@section scripts{

    <!--UtilitiesScripts [ Tiene las funciones especiales usadas en las vistas ]-->
    <script src="@Url.Content("~/Content/js/UtilitiesScripts.js")"></script>

   
}

IntelliPrestamos/Views/SetUp/_AddRoles.cshtml
@model IntelliPrestamos.Models.Roles
<!-- Modal -->
<div class="modal fade" id="modalDetail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Crear/Editar Registro</h4>
            </div>
            <div class="modal-body">
                <form id="AddConfigUpdate">

                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label"></label>
                                    @Html.HiddenFor(m => m.Id_Rol, new { @id = "Id_Rol" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                  
                                </div>
                            </div>
                        </div>
                        
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label" style="font-weight:bold;">Nombre Rol:</label>
                            @Html.TextBoxFor(m => m.Nombre_Rol, new { @class = "form-control", @id = "Nombre_Rol" })
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="form-group">
                                <label class="control-label" style="font-weight:bold;">Descripcion:</label>
                                @Html.TextBoxFor(m => m.Descripccion, new { @class = "form-control", @id = "Descripccion" })
                            </div>
                        </div>
                    </div>
                </div>                
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label" style="font-weight:bold;">Esta Activo:</label>
                            @Html.DropDownListFor(m => m.Activo, new List<SelectListItem>
                                                                             {
                                                                                new SelectListItem{ Text="Sí", Value = "1" },
                                                                                new SelectListItem{ Text="No", Value = "0" }
                                                                             }, new { @class = "form-control", @id = "Item_Type" })
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="form-group">
                               
                            </div>
                        </div>
                    </div>
                </div>
               

                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label" style="font-weight:bold;">Modulos:</label>
                            @if (Model.ListRol != null)
                            {
                                for (int i = 0; i < Model.ListRol.Count; i++)
                                {
                                    <div class="checkbox">                                        
                                        @Html.CheckBoxFor(m => m.ListRol[i].Selected)
                                        @Model.ListRol[i].Nombre
                                        @Html.HiddenFor(m => m.ListRol[i].Id_Modulos)
                                        @*@Html.HiddenFor(m => Model.ListRol[i].Nombre)*@                                        
                                    </div>
                                }
                            }
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                           
                        </div>
                    </div>
                </div>

            </div>
            <input type="hidden" value="@ViewBag.Id" id="id" name="id" />
        </form>
    </div>
    <div class="modal-footer">
        <span id="spnModalConfigInformation" style="color:red;"></span>
        <button type="button" class="btn btn-default" data-dismiss="modal" data-url="@(Url.Action("GetRoles", "SetUp"))" onclick="showRefreshViews(this, '_ViewRoles');">Cerrar</button>
        <button type="button" class="btn btn-primary" id="btnSaveModify" onclick="saveModalConfig(this, 'spnModalConfigInformation');" data-url="@(Url.Action("Add", "SetUp"))">Guardar</button>
    </div>
</div>
</div>
</div>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script type="text/javascript">
    $().ready(function () {
        // validate the contact form when it is submitted
        $("#AddConfigUpdate").validate({

            rules: {
                Nombre_Rol: { required: true },
                Descripccion: { required: true }
            },
            messages: {
                Nombre_Rol: "* Campo obligatorio",
                Descripccion: "* Campo obligatorio"
            }
        });

    });

</script>

IntelliPrestamos/Views/SetUp/_Delete.cshtml
@model IntelliPrestamos.Models.Empleado

<div class="panel">
    <!--Block Styled Form -->
    <!--===================================================-->

    <div class="panel">

        <!-- Panel heading -->
        <div class="panel-heading">
            <div class="panel-control">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#demo-tabs-box-1" aria-expanded="true"><i class="fa"></i>Datos Empleado</a></li>
                    <li class=""><a data-toggle="tab" href="#demo-tabs-box-2" aria-expanded="false"><i class="fa"></i>Datos Del Usuario</a></li>
                </ul>
            </div>
            <h3 class="panel-title">Agregar / Modificar Empleados</h3>
        </div>

        <!-- Panel body -->
        @using (Html.BeginForm("Add", "Users", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            <div class="panel-body">
                <div class="tab-content">

                    <!--SHOWING ERRORS IN TOOLTIP-->
                    <!--===================================================-->
                    <div id="demo-tabs-box-1" class="tab-pane fade active in">
                        <h4 class="mar-btm text-thin">Datos Empleado</h4>
                        <hr>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label">Nombre</label>
                                        <input type="text" class="form-control" value="@Model.Nombre" name="Nombre" id="Nombre" disabled="disabled">
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label">Apellidos</label>
                                        <input type="text" class="form-control" value="@Model.Apellidos" name="Apellidos" id="Apellidos" disabled="disabled">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label">Cedula</label>
                                        <input type="text" class="form-control" value="@Model.Cedula" name="Cedula" id="Cedula" disabled="disabled">
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label">Direccion</label>
                                        <input type="text" class="form-control" value="@Model.Direccion" name="Direccion" id="Direccion" disabled="disabled">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label">Telefono</label>
                                        <input type="text" class="form-control" value="@Model.Telefono" name="Telefono" id="Telefono" disabled="disabled">
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label">Celular</label>
                                        <input type="text" class="form-control" value="@Model.Celular" name="Celular" id="Celular" disabled="disabled">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label">Fecha Nacimiento</label>
                                        <div class="input-daterange input-group" id="datepicker">
                                            <input type="text" class="form-control" value="@Model.Fecha_Nacimiento" name="Fecha_Nacimiento" id="Fecha_Nacimiento" disabled="disabled">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label">Fecha Ingreso</label>
                                        <div class="input-daterange input-group">
                                            <input type="text" class="form-control" value="@Model.Fecha_Ingreso" name="Fecha_Ingreso" id="Fecha_Ingreso" disabled="disabled">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label">Cargo</label>
                                        @Html.DropDownListFor(m => m.Cargo_Id, @ViewBag.DrpCargo as IEnumerable<SelectListItem>, new { @class = "form-control", @id = "Cargo_Id", @disabled = "true" })
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label class="control-label">Supervisor</label>
                                            @Html.DropDownListFor(m => m.Id_Supervisor, @ViewBag.DrpSup as IEnumerable<SelectListItem>, new { @class = "form-control", @id = "Id_Supervisor", @disabled = "true" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="demo-tabs-box-2" class="tab-pane fade">
                        <h4 class="mar-btm text-thin">Datos Del Usuario</h4>
                        <hr>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label">Nombre Usuario</label>
                                        @Html.TextBoxFor(m => m.User.Usuario, new { @class = "form-control", @id = "Usuario", @disabled = "true" })
                                        @*<input type="text" class="form-control" value="@Model.User.Usuario" name="Usuario" id="Usuario">*@
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label">Clave</label>
                                        @Html.TextBoxFor(m => m.User.Clave, new { @class = "form-control", @id = "Clave", @disabled = "true" })
                                        @*<input type="number" class="form-control" value="@Model.User.Clave" name="Clave" id="Clave">*@
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label">Rol</label>
                                        @Html.DropDownListFor(m => m.User.Id_Rol, @ViewBag.DrpRol as IEnumerable<SelectListItem>, new { @class = "form-control", @disabled = "true" })
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">

                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
            <div class="panel-footer clearfix">
                <div class="panel-footer text-right">
                    <span id="spnModalConfigInformation" style="color:red;"></span>
                    <button type="button" class="btn btn-default" data-dismiss="modal" data-url="@(Url.Action("Get", "Users"))" onclick="showRefreshViews(this, '_View');">Cerrar</button>
                    <button type="button" class="btn btn-primary" id="btnSaveModify" onclick="saveModalConfig(this, 'spnModalConfigInformation');" data-url="@(Url.Action("Delete", "Users"))">Inhabilitar</button>
                </div>
            </div>
        }
    </div>
    <!--===================================================-->
    <!--End Block Styled Form -->

</div>

@section scripts{
    <script src="@Url.Content("~/Content/plugins/bootstrap-validator/bootstrapValidator.min.js")"></script>

}

IntelliPrestamos/Views/SetUp/_DeleteRoles.cshtml
@model IntelliPrestamos.Models.Roles
<!-- Modal -->
<div class="modal fade" id="modalDetail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Inhabilitar Registro</h4>
            </div>
            <div class="modal-body">
                <form id="AddConfigUpdate">

                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label"></label>
                                    @Html.HiddenFor(m => m.Id_Rol, new { @id = "Id_Rol" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">

                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label" style="font-weight:bold;">Nombre Rol:</label>
                                    @Html.TextBoxFor(m => m.Nombre_Rol, new { @class = "form-control", @id = "Nombre_Rol", @readonly = "true" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-group">
                                        <label class="control-label" style="font-weight:bold;">Descripcion:</label>
                                        @Html.TextBoxFor(m => m.Descripccion, new { @class = "form-control", @id = "Descripccion", @readonly = "true" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label" style="font-weight:bold;">Esta Activo:</label>
                                    @Html.DropDownListFor(m => m.Activo, new List<SelectListItem>
                                                                             {
                                                                                new SelectListItem{ Text="Sí", Value = "1" },
                                                                                new SelectListItem{ Text="No", Value = "0" }
                                                                             }, new { @class = "form-control", @id = "Activo", @readonly = "true" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-group">

                                    </div>
                                </div>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label" style="font-weight:bold;">Modulos:</label>
                                    @if (Model.ListRol != null)
                                    {
                                        for (int i = 0; i < Model.ListRol.Count; i++)
                                        {
                                            <div class="checkbox">
                                                @Html.CheckBoxFor(m => m.ListRol[i].Selected, new {  @disabled = "true" })
                                                @Model.ListRol[i].Nombre                                               
                                            </div>
                                        }
                                    }
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">

                                </div>
                            </div>
                        </div>

                    </div>
                    <input type="hidden" value="@ViewBag.Id" id="id" name="id" />
                </form>
            </div>
            <div class="modal-footer">
                <span id="spnModalConfigInformation" style="color:red;"></span>
                <button type="button" class="btn btn-default" data-dismiss="modal" data-url="@(Url.Action("GetRoles", "SetUp"))" onclick="showRefreshViews(this, '_ViewRoles');">Cerrar</button>
                <button type="button" class="btn btn-primary" id="btnSaveModify" onclick="saveModalConfig(this, 'spnModalConfigInformation');" data-url="@(Url.Action("Delete", "SetUp"))">Inhabilitar</button>

            </div>
        </div>
    </div>
</div>