IntelliPrestamos/Controllers/CargoController.cs
using IntelliPrestamo.AccessLayer.DataManager;
using IntelliPrestamos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IntelliPrestamos.Controllers
{
    public class CargoController : BaseController.BaseController
    {
            private CargoManager manager;
        //
        // GET: /Cargo/
        
        public ActionResult Manage()
        {
            bussinessInfo();
            return GetAll("");
        }

        public ActionResult Get(int Id_Rol, string partial_view)
        {
            manager = new CargoManager();
            var result = manager.Get(Id_Rol);

            return PartialView(partial_view, result);
        }

        public ActionResult GetAll(string partial_view)
        {
            manager = new CargoManager();
            var result = manager.Get();
            #region PreparandoArchivoDescarga
            string fileName = "Cargos.csv";
            //Areglando lista.
            var dataReport = (from a in result
                              select new
                              {
                                  Id_Cargo = a.Id_Cargo.ToString(),
                                  Nombre = a.Nombre,
                                  EsAccionista = a.EsAccionista.ToString(),
                                  EsGerencial = a.EsGerencial.ToString()
                              }
                ).ToList();
            Create_Excel_Reports(fileName, dataReport);
            #endregion
            if (string.IsNullOrEmpty(partial_view))
            {
                return View(result);
            }
            return PartialView(partial_view, result);
        }
        
        public ActionResult Add(Cargo model)
        {
            try
            {
                manager = new CargoManager();
                manager.Set(model);

                ViewBag.Success = "Datos Actualizados Satisfactoriamente";
                return Content("Datos Actualizados Satisfactoriamente");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }

            return Content(ViewBag.Error);
        }
        public ActionResult Delete(Cargo model)
        {
            try
            {
                manager = new CargoManager();
               manager.Del(model);

                ViewBag.Success = "Datos Actualizados Satisfactoriamente";
                return Content("Datos Actualizados Satisfactoriamente");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }

            return Content(ViewBag.Error);
        }
	}
}

IntelliPrestamos/Views/Cargo/Manage.cshtml
@model IEnumerable<IntelliPrestamos.Models.Cargo>
@{
    ViewBag.Title = "Gestión De Cargos En Sistema";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <div class="panel-control">
            <a class="fa fa-question-circle fa-lg fa-fw unselectable add-tooltip" href="#" data-original-title="<h4 class='text-thin'>Información</h4><p style='width:150px'>Este modulo muestra los Modulos de seguridad configurados en sistema.</p>" data-html="true" title=""></a>
        </div>
        <h3 class="panel-title">Gestión De Cargos En Sistema</h3>
    </div>

    <div class="panel-body">
        <div class="pad-btm form-inline">
            <div class="row">
                <div class="col-sm-6 table-toolbar-left">
                    <button id="demo-btn-addrow" class="btn btn-purple btn-labeled fa fa-plus" data-url="@(Url.Action("Get", "Cargo"))" onclick="showModalConfig(this, '0','_Add');">Crear</button>
                </div>
                <div class="col-sm-6 table-toolbar-right">
                    <div class="form-group">

                    </div>
                </div>
            </div>
        </div>
        <div id="content-ajax">
            @Html.Partial("~/Views/Cargo/_View.cshtml", Model)
        </div>
        <div id="content-modal_info"></div>
    </div>
</div>
@section Header{

    <link href="@Url.Content("~/Content/plugins/datatables/media/css/dataTables.bootstrap.css")" rel="stylesheet">
}
@section scripts{

    <!--UtilitiesScripts [ Tiene las funciones especiales usadas en las vistas ]-->
    <script src="@Url.Content("~/Content/js/UtilitiesScripts.js")"></script>


}

IntelliPrestamos/Views/Cargo/_Add.cshtml
@model IntelliPrestamos.Models.Cargo
<!-- Modal -->
<div class="modal fade" id="modalDetail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Crear/Editar Cargo</h4>
            </div>
            <div class="modal-body">
                <form id="AddConfigUpdate">
                    @Html.AntiForgeryToken()
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label"></label>
                                    @Html.HiddenFor(m => m.Id_Cargo, new { @id = "Id_Cargo" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">

                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label" style="font-weight:bold;">Nombre:</label>
                                    @Html.TextBoxFor(m => m.Nombre, new { @class = "form-control", @id = "Nombre" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-group">
                                        <label class="control-label" style="font-weight:bold;">Es Gerencial:</label>
                                        @Html.DropDownListFor(m => m.EsGerencial, new List<SelectListItem>
                                                                             {
                                                                                new SelectListItem{ Text="Sí", Value = "1" },
                                                                                new SelectListItem{ Text="No", Value = "0" }
                                                                             }, new { @class = "form-control", @id = "EsGerencial" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label" style="font-weight:bold;">Es Accionista:</label>
                                    @Html.DropDownListFor(m => m.EsAccionista, new List<SelectListItem>
                                                                             {
                                                                                new SelectListItem{ Text="Sí", Value = "1" },
                                                                                new SelectListItem{ Text="No", Value = "0" }
                                                                             }, new { @class = "form-control", @id = "EsAccionista" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-group">
                                        <label class="control-label" style="font-weight:bold;">Activo:</label>
                                        @Html.DropDownListFor(m => m.Activo, new List<SelectListItem>
                                                                             {
                                                                                new SelectListItem{ Text="Sí", Value = "1" },
                                                                                new SelectListItem{ Text="No", Value = "0" }
                                                                             }, new { @class = "form-control", @id = "Activo" })
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <input type="hidden" value="@ViewBag.Id" id="id" name="id" />
                </form>
            </div>
            <div class="modal-footer">
                <span id="spnModalConfigInformation" style="color:red;"></span>
                <button type="button" class="btn btn-default" data-dismiss="modal" data-url="@(Url.Action("GetAll", "Cargo"))" onclick="showRefreshViews(this, '_View');">Cerrar</button>
                <button type="button" class="btn btn-primary" id="btnSaveModify" onclick="saveModalConfig(this, 'spnModalConfigInformation');" data-url="@(Url.Action("Add", "Cargo"))">Guardar</button>
            </div>
        </div>
    </div>
</div>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script type="text/javascript">
    $().ready(function () {
        // validate the contact form when it is submitted
        $("#AddConfigUpdate").validate({

            rules: {
                Nombre: { required: true }
            },
            messages: {
                Nombre: "* Campo obligatorio"
            }
        });

    });

</script>

IntelliPrestamos/Views/Cargo/_Delete.cshtml
@model IntelliPrestamos.Models.Cargo
<!-- Modal -->
<div class="modal fade" id="modalDetail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar</h4>
            </div>
            <div class="modal-body">
                <form id="AddConfigUpdate">

                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label"></label>
                                    @Html.HiddenFor(m => m.Id_Cargo, new { @id = "Id_Cargo" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">

                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label" style="font-weight:bold;">Nombre:</label>
                                    @Html.TextBoxFor(m => m.Nombre, new { @class = "form-control", @id = "Nombre", @disabled = "true" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-group">
                                        <label class="control-label" style="font-weight:bold;">Es Gerencial:</label>
                                        @Html.DropDownListFor(m => m.EsGerencial, new List<SelectListItem>
                                                                             {
                                                                                new SelectListItem{ Text="Sí", Value = "1" },
                                                                                new SelectListItem{ Text="No", Value = "0" }
                                                                             }, new { @class = "form-control", @id = "EsGerencial", @disabled = "true" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label" style="font-weight:bold;">Es Accionista:</label>
                                    @Html.DropDownListFor(m => m.EsAccionista, new List<SelectListItem>
                                                                             {
                                                                                new SelectListItem{ Text="Sí", Value = "1" },
                                                                                new SelectListItem{ Text="No", Value = "0" }
                                                                             }, new { @class = "form-control", @id = "EsAccionista", @disabled = "true" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-group">
                                        <label class="control-label" style="font-weight:bold;">Activo:</label>
                                        @Html.DropDownListFor(m => m.Activo, new List<SelectListItem>
                                                                             {
                                                                                new SelectListItem{ Text="Sí", Value = "1" },
                                                                                new SelectListItem{ Text="No", Value = "0" }
                                                                             }, new { @class = "form-control", @id = "Activo", @disabled = "true" })
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <input type="hidden" value="@ViewBag.Id" id="id" name="id" />
                </form>
            </div>
            <div class="modal-footer">
                <span id="spnModalConfigInformation" style="color:red;"></span>
                <button type="button" class="btn btn-default" data-dismiss="modal" data-url="@(Url.Action("GetAll", "Cargo"))" onclick="showRefreshViews(this, '_View');">Cerrar</button>
                <button type="button" class="btn btn-primary" id="btnSaveModify" onclick="saveModalConfig(this, 'spnModalConfigInformation');" data-url="@(Url.Action("Delete", "Cargo"))">Eliminar</button>
            </div>
        </div>
    </div>
</div>

IntelliPrestamos/Views/Cargo/_Get.cshtml
@model IntelliPrestamos.Models.Cargo
<!-- Modal -->
<div class="modal fade" id="modalDetail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Visualizar</h4>
            </div>
            <div class="modal-body">
                <form id="AddConfigUpdate">

                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label"></label>
                                    @Html.HiddenFor(m => m.Id_Cargo, new { @id = "Id_Cargo" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">

                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label" style="font-weight:bold;">Nombre:</label>
                                    @Html.TextBoxFor(m => m.Nombre, new { @class = "form-control", @id = "Nombre", @disabled = "true" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-group">
                                        <label class="control-label" style="font-weight:bold;">Es Gerencial:</label>
                                        @Html.DropDownListFor(m => m.EsGerencial, new List<SelectListItem>
                                                                             {
                                                                                new SelectListItem{ Text="Sí", Value = "1" },
                                                                                new SelectListItem{ Text="No", Value = "0" }
                                                                             }, new { @class = "form-control", @id = "EsGerencial", @disabled = "true" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label" style="font-weight:bold;">Es Accionista:</label>
                                    @Html.DropDownListFor(m => m.EsAccionista, new List<SelectListItem>
                                                                             {
                                                                                new SelectListItem{ Text="Sí", Value = "1" },
                                                                                new SelectListItem{ Text="No", Value = "0" }
                                                                             }, new { @class = "form-control", @id = "EsAccionista", @disabled = "true" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-group">
                                        <label class="control-label" style="font-weight:bold;">Activo:</label>
                                        @Html.DropDownListFor(m => m.Activo, new List<SelectListItem>
                                                                             {
                                                                                new SelectListItem{ Text="Sí", Value = "1" },
                                                                                new SelectListItem{ Text="No", Value = "0" }
                                                                             }, new { @class = "form-control", @id = "Activo", @disabled = "true" })
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <input type="hidden" value="@ViewBag.Id" id="id" name="id" />
                </form>
            </div>
            <div class="modal-footer">
                <span id="spnModalConfigInformation" style="color:red;"></span>
                <button type="button" class="btn btn-default" data-dismiss="modal" >Cerrar</button>
                
            </div>
        </div>
    </div>
</div>

IntelliPrestamos/Views/Cargo/_View.cshtml
@model IEnumerable<IntelliPrestamos.Models.Cargo>
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <caption>
            @if (ViewBag.DownloadLink != null)
            {
                <a href="../TmpFiles/@ViewBag.DownloadLink" class="btn btn-mint btn-rounded">Descargar Excel</a>
            }
        </caption>
        <thead>
            <tr>
                <th style="width:4ex"></th>
                <th>Cargo ID</th>
                <th>Nombre</th>
                <th>Es Gerencial</th>
                <th>Es Accionista</th>
                <th>Activo</th>
                <th class="text-right">Acción</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a onclick="showModalConfig(this,  '@(item.Id_Cargo)', '_Get');" style="cursor: pointer; color: #337ab7;" data-url="@(Url.Action("Get", "Cargo"))">Visualizar</a>
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.Id_Cargo)</td>
                    <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                    <td>
                        @if (item.EsGerencial != null && item.EsGerencial == 1)
                        {
                            <span>Si</span>
                        }
                        else
                        {
                            <span>No</span>
                        }
                    </td>
                    <td>
                        @if (item.EsAccionista != null && item.EsAccionista == 1)
                        {
                            <span>Si</span>
                        }
                        else
                        {
                            <span>No</span>
                        }
                    </td>
                    <td>
                        @if (item.Activo != null && item.Activo == 1)
                        {
                            <span>Si</span>
                        }
                        else
                        {
                            <span>No</span>
                        }
                    </td>
                    <td class="text-right">
                        <a class="btn btn-xs btn-default add-tooltip" data-toggle="tooltip" onclick="showModalConfig(this, '@(item.Id_Cargo)','_Add');" data-original-title="Editar" data-container="body" data-url="@(Url.Action("Get", "Cargo"))"><i class="fa fa-pencil"></i></a>
                        <a class="btn btn-xs btn-danger add-tooltip" data-toggle="tooltip" onclick="showModalConfig(this,  '@(item.Id_Cargo)', '_Delete');" data-original-title="Eliminar" data-container="body" data-url="@(Url.Action("Get", "Cargo"))"><i class="fa fa-times"></i></a>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>

<script type="text/javascript">
    $(function () {
        $('.table').DataTable({
            "language": {
                "lengthMenu": "Mostrar _MENU_ Registros por Página",
                "zeroRecords": "No se encontraron coincidencias",
                "info": "Mostrando Página _PAGE_ de _PAGES_",
                "infoEmpty": "",
                "search": "Buscar:",
                "infoFiltered": "(filtered from _MAX_ total records)",
                "paginate": {
                    "first": "Primero",
                    "last": "Último",
                    "next": "Próximo",
                    "previous": "Anterior"
                }
            }
        });
    });
</script>